### ISSUE TITLE
FFT implementation

### ISSUE THREAD

**Issue by yoelsh** [ComputationalCryoEM/ASPIRE-Python#127]
/src/aspire/utils/fft.py uses scipy FFT and not FFTW which is supposed to be much faster.
What is the reason for that?

**Comment by junchaoxia** [comment]
I think there is no specific reason for this. The first developer started it without considering too much about the performance. We should be able to replace it and even with the GPU version too. Overall, we did not focus too much on performance yet.

**Comment by vineetbansal** [comment]
Junchao..there's a facade module in `numeric` that should allow you to switch to `pyfftw` with minimal pain.

**Comment by garrettwrong** [comment]
We use the facade module (which currently is just a wrapper for FFTW) in ApplePicker for example.  Ideally I'd like to see one entity used consistently throughout the code.  Right now we do traditional FFT no less than three ways :).

Since we are targeting a hybrid code (one that can work host or with a GPU), the `numeric` module probably makes the most sense long term...  Using cupy FFT, exposed via this module, was one of the ideas worked on at the hackathon. We'd just need to take a lot more care to integrate it into `develop` in an effective way.

I sort of view that all as the same issue.. so I am going to add this to the hackathon board.

**Comment by junchaoxia** [comment]
Since we have finished implementing the facade modules for FFT in PR #269, we can start to replace the FFT functions in the submodules. The list below are major files we should replace.

1) `aspire/basis/ffb_2d.py`
2) `aspire/estimation/covar.py` 
3) `aspire/estimation/kernel.py`
4) `aspire/estimation/mean.py`
5)  `aspire/image/__init__.py`
6) `aspire/utils/fft.py` 
7) `aspire/utils/preprocess.py`
8) `aspire/volume/__init__.py`

**Comment by janden** [comment]
Good. Let's take them submodule by submodule in different PRs.

**Comment by junchaoxia** [comment]
The FFT implementation of APPLE-Picker submodule has been done in PR #269. For the rest submodules there are some additional improvements need to be done although replacements of statements are relative directly (also not too many replacements).  The tasks can be assigned to two major PRs as below:
 
PR 1 (submitted as #298): 

> 1) Implement centered FFT functions and unit tests for all facade modules.
> 2) Make all three options (pyfftw, scipy, and cupy) available for all FFT calculations in Image, Volume, Basis, and Preprocess classes.

PR 2:

> 1) Include an additional variable, the length of the transformed axis of the output, into the parameter lists of our customized FFT functions.
> 2) Perform corresponding replacements in the Cov3D submodule.  
> 3) Remove the old implementation of centered FFTs in src/aspire/utils/fft.py.

**Comment by janden** [comment]
Where are we on this?

**Comment by junchaoxia** [comment]
The lists in PR 2 need to be finished.

**Comment by janden** [comment]
Ok thank you.

**Comment by garrettwrong** [comment]
It looks to me like this might only be one gallery file using straight np.fft, and I am actually totally fine with that because it is how a user is most likely to do it anyway.

OTOH, I didn't review manually.  Just grep'ed few ways.

This should be an easy issue to close. Triaging into 0.9.1.

**Comment by garrettwrong** [comment]
Josh, can you check where we are (or are not..) using our FFT facade in the codebase?

If we are using it everywhere we can close this issue.  Otherwise, lets document what still needs to be done and see if we can complete it.

**Comment by garrettwrong** [comment]
A simple grep yielded that in our code we are using scipy fftpack for covar3d, kernel.py, and mean.py.

We are additionally using in `gallery/tutorials/basic_image_array.py` but I'm okay with disregarding that for the purpose of this issue.

Mainly the calls are to `fftn`, which we provide a wrapper for.  I will see what happens when we use our wrapper.

**Comment by garrettwrong** [comment]
Closed by #763.  All FFT calls should now be using ASPIRE's fft interface.

It is possible to implement further PyFFTW tuning within the facade.
