### ISSUE TITLE
Build a developer list

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#136]
There is no unique place to list the names of all developers although there is a couple of places mentioning this. A separate file might be necessary.

**Comment by garrettwrong** [comment]
There are a few "bots" that can use the github API (below) in addition to manual entries.  One is All-Contributors.  My opinion is that a simple table might be easier, particularly because some contributors will probably predate this repo. I will push an example momentarily for discussion.

https://api.github.com/repos/ComputationalCryoEM/ASPIRE-Python/contributors

**Comment by garrettwrong** [comment]
There is now a top of package table in rst format that can be maintained. The same is parsed into the sphinx docs. Closing.
