### ISSUE TITLE
deprecate anorm method 

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#185]
`anorm` and maybe the related `ainner` appears to have some bugs found while checkout out a warning in #182 #181 .

I am suggesting to replace with numpy norm. Because this turned out to be more then a benign warning, and will touch some other code.. I'm making a separate issue.

**Comment by garrettwrong** [comment]
OoOOoo, I see what happened here ;). 

So in the entire code, only the one case like below (`simulation.py`) and the calls from `acorr` in the same file cannot be directly replaced by a `np.linalg.norm(axis=None)`.

Probably should look at `ainner` too, see what we're doing there.

```
>>> x = np.random.randn(3,4,5,6)
>>> a  = _anorm(x, (0,1,2))
/scratch/Dropbox/PU/aspire/ASPIRE-Python.dev/src/aspire/utils/matrix.py:304: RuntimeWarning: invalid value encountered in sqrt
  return np.sqrt(ainner(x, x, axes))
>>> x = np.random.randn(3,4,5,6)
>>> a  = _anorm(x, (0,1,2))
>>> da = np.diag(a); da
array([7.99572695, 7.87712605, 8.20171272, 6.85448784, 7.66760348,
       7.88795795])
>>> np.array([norm(x[...,c]) for c in range(x.shape[-1])])
array([7.99572695, 7.87712605, 8.20171272, 6.85448784, 7.66760348,
       7.88795795])
```

**Comment by janden** [comment]
Yeah norm will only work on two axes or all of them. As you have in the example above, we may want to compare a set of volumes and get the per-volume norm. (So we'll have four dimensions and only compute the norm along three.)

This is why having a separate function (like `anorm`) might be useful, since we're doing a lot of norms on higher-dimensional arrays. Then we'd default to that instead of having two functions: `np.linalg.norm` for summing over one, two, or all the dimensions, and another `anorm` for all the other cases.

**Comment by garrettwrong** [comment]
Right, yes, I have something local with the per volume... that is correct, I didn't have time to push more before meeting.

We only seem to perform this once outside of `acorr`. If it is useful I can probably do the einsum thing.  Not really interested in taking the diag of junk even though I was able to make it work..

Really the right thing might be to make a request to numpy... We are probably not the only ones... They might actually fix it, or just offer to let us fix it :D.

**Comment by janden** [comment]
> We only seem to perform this once outside of acorr. If it is useful I can probably do the einsum thing. Not really interested in taking the diag of junk even though I was able to make it work..

Right. Why not just call `np.sum(x * y, axis=…)`? It might not be the fastest, but these things aren't called in inner loops, as far as I can tell.

> Really the right thing might be to make a request to numpy... We are probably not the only ones... They might actually fix it, or just offer to let us fix it :D.

Sounds reasonable. On the other hand, they maybe have this behavior for a reason? I guess we will find out.

**Comment by garrettwrong** [comment]
Agreed, speed isn't an issue here. Those few failing test were actually because I didn't put the root in for the corner case. This time they failed on my bad code :D.  Everything seems okay now, 99% numpy norm, tests passing, no warning.

Regarding numpy, I think the case is ambiguous to them due to their assumption about broadcasting over 2d matrices, so it would require an additional argument like ndim in conjunction with the axes for broadcasting over k-d matrices. I'll save this for some meeting laden day. Even if it goes in, it will be a while to trickle down.

Going to keep this open, for the discussion history, but changing labels since the change is covered in an associated PR.

**Comment by janden** [comment]
I'm still not sure we want to do this. Right now, `np.linalg.norm` works if: 1) we're summing over all dimensions or 2) we're summing over one or two dimensions. For other cases (like summing over three dimensions), we need a different function (currently `anorm`). Wouldn't it be cleaner to just call one function consistently (`anorm`) instead of choosing between functions depending on the particular configuration of axes we're considering?

That doesn't mean we shouldn't simplify `anorm` to do something more reasonable than calling `np.diag(np.tensordot(…))`, such as something like `np.sum(x * x, …)` (or calling `np.linalg.norm` in special cases to get a potential speedup). It seems that this has been the underlying problem rather than calling.

**Comment by garrettwrong** [comment]
Sure, I just saw we only needed `anorm` for `acorr` in the same file and a single line elsewhere... All others were implemented as 1.  I guess if there will be more than one exception in the future what you suggest makes more sense to me too. I can change the PR, if you want to hold off on any review action (setting to draft now).

**Comment by janden** [comment]
Ok. It just occurred to me when I was looking through the PR that we may want to have finer control over these things (looks like it's used in `vol_coords`, for example). Maybe it occurs mostly in interactive work right now, but I don't think it'll be that rare.. For example, computing the relative mean squared error of some collection of images would be
```
anorm(im_est - im_true, axes=(-2, -1)) ** 2 / anorm(im_true, axes=(-2, -1)) ** 2
```

**Comment by garrettwrong** [comment]
Merged, closing.
