### ISSUE TITLE
Code in ASPIRE shouldn't break Python (src/aspire/aspire)

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#202]
I was going to try and work a seemingly trivial issue (#5 ) that lives solely in `src/aspire/aspire/preprocessor.py` and uncovered a bit of a mess.  I found that inserting false asserts and raises does not cause any unit tests to fail (okay fine, but not a great start).  So this file is not imported by anything in our test suite at all, rather it is imported by things in `aspire.commands`.  Okay, so I tried to just let python parse those command files (mainly to see if I got a help menu or something) and was met with several different modes of failure. As they sit, I am concerned none of those tools work in our current repo (they break importing packages in a clean env, if they are even the correct packages anymore, etc).

Is this `PreProcessor` and commands stuff vestigial code? Or code that is needed for something in the future? Am I doing something wrong? Does it have any tests we can add or documentation? 

I guess generally my question is what's the plan for this code...

Here is one failure
```
python src/aspire/commands/denoise.py
Traceback (most recent call last):
  File "src/aspire/commands/denoise.py", line 5, in <module>
    from aspire.basis.ffb_2d import FFBBasis2D
  File "/scratch/Dropbox/PU/aspire/ASPIRE-Python.dev/src/aspire/commands/aspire.py", line 8, in <module>
    from aspire.aspire.abinitio import Abinitio
ModuleNotFoundError: No module named 'aspire.aspire'; 'aspire' is not a package
```
Depending which level of the tree you run it, you might also get seg faults because we named a package `io`. :D

**Comment by junchaoxia** [comment]
It might be that you did not run the commands in the right way. The commands are implemented by `click` package and managed by modules.  Run  any commands,  we need to do two similar steps as below:  

1) Set conda and aspire environments: 
    module load anaconda3/5.3.0
    conda activate aspire
    export PYTHONPATH=/tigress/junchaox/software/ASPIRE-Python_git/src

2) python -m aspire denoise [OPTIONS]

You can run `python -m aspire --help` to see what other commands available besides `denoise.` Some of commands are from old Python code under src/aspire/asire folder, and  some of them are added based on new framework.  A tutorial example should go through all steps later before the formal release.

**Comment by garrettwrong** [comment]
Could definitely be that :). Okay, cool, thanks Junchao. Is that like written down anywhere I can read?  Using -m did do something.  Are we sure this stuff is implemented correctly? This seems odd to me... I would expect that if python has trouble parsing these files that we are in for a very bad time later...

Do you know if there are any basic "tests" for these commands? Thanks

```
(base) ➜  ASPIRE-Python.dev git:(rm_box_issue5) python -m aspire --help                                                                                                            
/home/garrett/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
Usage: aspire [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  abinitio          Abinitio algorithm
  apple             Pick and save particles from one or more mrc files.
  classify          Classification-Averaging algorithm
  compare           Compare 2 stack files
  cov3d             Estimate mean volume and covariance from a starfile.
  crop              Crop/Pad projections in stack
  denoise           Denoise the images and output the clean images using
                    the...
  downsample        Downsample projections in stack
  global_phaseflip  Apply global phase-flip to an MRC stack
  inspect           Show stack size/type
  normalize         Normalize background
  piped-cli         Piped cli accepts multiple commands, executes one by
                    one...
  prewhitten        Prewhitten projections in stack
  save              Save MRC stack to output file
  viewstack         Plot projections in stack file
```

**Comment by junchaoxia** [comment]
By the way, all the code under  `src/aspire/asire` folder is from old Python code and there are no any related unit tests. Probably it not necessary to list them as issues before we clean up and merge into the new framework.

**Comment by garrettwrong** [comment]
Understood it is from the old repo.  I figured we at lest had run the commands to see if they worked, maybe had the invocations squirreled away somewhere. No problem. Consider this the first issue of the sort then :). Thanks!

**Comment by junchaoxia** [comment]
Those commands are used to perform calculations on experimental data. They call modules that generally are tested through unit tests under `tests` folder. I think it is not necessary to develop unit tests again. But there can be another level of tests for them by reproducing the results from tutorial examples. Usually it will take much longer time.

**Comment by garrettwrong** [comment]
We should not accept having an entire directory of untested code as our user facing API.

**Comment by junchaoxia** [comment]
Unfortunately, most of old code, Python or Matlab are in this style. Developing unit tests and reproducing consistent results are most time-consuming work.

**Comment by janden** [comment]
The code in `src/aspire/aspire` is indeed old (legacy) code which has not yet been integrated into the new framework. Among other things, this means that it is not tested. Since this code included public-facing command-line invocations, I assume that these were simply carried over when the old and new code was brought together. I agree that this is not a great situation. This is why bringing in that code (refactoring and adding tests) is a main priority for the project.

We have two options:
– Add tests for the legacy code. Besides basic smoke tests to make sure things crash, I'm worried that this would take too much work, especially considering that our goal is to deprecate all this in the medium term. More broadly, parts of the code is structured around file-based I/O, which makes testing more complicated (but by no means unsurmountable).
– Remove the legacy code from the public interface. This would obviously reduce the usefulness of the package, but considering that the legacy code seems to be broken (how severely is not clear), that usefulness is clearly not there.

**Comment by garrettwrong** [comment]
My calling it broken may have been a little harsh (I was a little disappointed at the time). Saying it works by a hack is probably more pragmatic.  For my understanding, is this the primary interface to the code?

**Comment by janden** [comment]
> My calling it broken may have been a little harsh (I was a little disappointed at the time). Saying it works by a hack is probably more pragmatic.

Eh seems to be broken from what you're describing. Maybe be fixable, but it's code that's gone untested for quite a while, so it's not clear what state it's in. (There was, for example, #98 which was unresolved for a long time.)

> For my understanding, is this the primary interface to the code?

In the old code, yes. For the new code, I envision the library to be the primary interface first, then we'll redesign the command line commands to work on top of that.

**Comment by junchaoxia** [comment]
Yoel sent me a list to go through steps to rebuilt a 3D volume using the old Python code before the Hackathon. I will spend some time to repeat the steps this week or not. By the way, the documentation on using commands is drafted on    https://computationalcryoem.github.io/ASPIRE-Python/quickstart.html. Of course, that is only a very short introduction which needs to be developed further.

**Comment by junchaoxia** [comment]
The initial goal for this issue is for unit tests for preprocessor under src/aspire/aspire but this is being extracted to the new framework and it is not necessary for the old one. I am closing this one since I created #234 for the corresponding topics in new framework.

**Comment by garrettwrong** [comment]
Why are we closing this when the broken code and imports are still in the repo? Seems like we didn't really do anything other than hide defects.

**Comment by junchaoxia** [comment]
I am not sure what is broken in your case. I checked my test cases before.  I was able to  run `denoise` as `python -m aspire denoise --starfile_in ./shiny_2sets_shift.star  --starfile_out ./Denoise/particles_denoise.star --pixel_size 1.34 --max_resolution 360 --data_folder ./ --max_rows 10000`,  run `classify` as "python -m aspire classify /scratch/gpfs/junchaox/cryoem-data/10028L65/whitened.mrcs", and run `abinitio` as `python -m aspire abinitio whitened_classified_subset.mrcs`.  But there are not related to unit tests. I will switch to a different title and make it more sense for the old set of python code if you would like to keep it open.

**Comment by janden** [comment]
So if I understand correctly, the reason that
```
python src/aspire/commands/denoise.py
```
fails is that there's the file `src/aspire/commands/aspire.py`, which clobbers the main `aspire` package, so when we have the line `from aspire.basis.ffb_2d`, it tries to load that `aspire.py` file, which is when things start going downhill. (Renaming that file causes `denoise` to work again.) I don't know if there's a standard way to tell Python to remove the current working directory from `sys.path`. Seems like `-m` does turn that off. Simplest thing to do might just be to rename `aspire.py` to something more specific.

**Comment by junchaoxia** [comment]
We are trying to using the CLICK command interface from the original Python package. In that way, the `aspire` is set to the main module and others such as `cov3d`, `denoise` (cov2d), `classify` and `abinitio` are submodules. The format to run a submodule function is `python -m aspire submodule paramter_list` not calling the python file.  There is a short introduction in the quick start page,  https://computationalcryoem.github.io/ASPIRE-Python/quickstart.html.  We need explain more in future if we decide to use CLICK.

**Comment by garrettwrong** [comment]
I think we're missing a main concern here, and we've now renamed the issue to have even less to do with the original problem.  I would appreciate if we don't rename other people's issues if we don't understand the content. That is pretty lame.

There should be no Python code in our code base that cannot simply be parsed by Python.  That is a glaring bug.  It will break pretty much any tool that is not explicitly configured to ignore it. I understand that there exists a specific command that circumvents this problem. Clearly that is the only one that was tested.  We've spent considerable effort deflecting when the fix is probably a few lines of code.

`python src/aspire/commands/denoise.py`
```
Traceback (most recent call last):
  File "src/aspire/commands/denoise.py", line 5, in <module>
    from aspire.basis.ffb_2d import FFBBasis2D
  File "/home/garrett/Dropbox/PU/aspire/ASPIRE-Python.dev/src/aspire/commands/aspire.py", line 8, in <module>
    from aspire.aspire.abinitio import Abinitio
ModuleNotFoundError: No module named 'aspire.aspire'; 'aspire' is not a package
```

Everything else in here is just noise.  This is my fault for trying to have a multi faceted conversation.

I am renaming this to something more appropriate.

**Comment by garrettwrong** [comment]
We should probably make separate issues about the API (its functionality, testing, future etc) at an appropriate time; I don't know that they are relevant near term.

**Comment by junchaoxia** [comment]
The python files under src/aspire/commands/ are used to group CLICK commands into different submodules. `aspire.py` is from the original Python code with corresponding functionalities. We agreed to follow the same CLICK design last year when we pulled in all parts of code from different repos.  `apple.py`,    `cov3d.py` and    `denoise.py` were added for corresponding submodules in the new framework. We are not expected to run those files directly since they are not executable scripts. There are even no statements such as `if __name__ == "__main__": `.   `aspire.py` includes many CLICK commands and they can not be run individually even we make it executable. That is why I said running them in the CLICK way `python -m aspire submodule paramter_list`.

**Comment by janden** [comment]
> There should be no Python code in our code base that cannot simply be parsed by Python.

So if I understand correctly, there's two ways Python code can be run: 1) as a top-level script and 2) as an imported module. As we know, the different execution modes lead to different rules about how imports are handled (it seems that `sys.path[0]` is the script directory in 1) but the CWD in 2)). If we run code as top-level scripts, it will look in the script directory before the rest of the path, which leads to conflicts.

This doesn't appear just in `src/aspire/commands/denoise.py` but whenever there's a sibling package or module called `aspire`. For example `python src/aspire/__init__.py` and `python src/aspire/__main__py` both fail (since they will try to import `aspire.aspire` instead of `aspire`). They all work when run as modules, however.

So we have two options:
1) Never allow modules or packages named `aspire` (except for the root, of course). This would mean renaming `aspire.aspire` to something like `aspire.legacy` and `aspire.commands.aspire` to `aspire.commands.entry` (or something). From a quick search, these are the only potential trouble spots.
2) Work under the assumption that all code in `src` will be run as a module, never as a top-level script.

I would opt for 2), but if this will break most toolchains, that's a problem. A quick check of `pytest` indicates that it seems to run the code as modules rather than top-level scripts, but that's obviously quite a limited survey.

**Comment by vineetbansal** [comment]
@janden .. great recap!

While I agree with (2), and that's the implicit assumption that led to our coding up the `commands` submodule the way we did, I think there's some value to not impose that restriction, since a lot of developers expect to add a `if __name__ == '__main__'` to a module (or a piece of code that will eventually turn into a module) and test it out real quick as a script, or a situation that Garrett ran into where he was just trying to explore some code by trying to run it.

So I'd say in this case we rename the 2 modules to not use the root module name like you suggest, and keep an eye out for this in the future.

**Comment by garrettwrong** [comment]
Code in question has been removed in #283 . Closing.
