### ISSUE TITLE
Eigensolver in estimate_rotation

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#211]
After discussing with Yoel, and reviewing in our dev meeting, the eigen solver used in the python code was changed from `eigs` ~> `eigsh` to better match the original Matlab code.  The input array is perfectly symmetric by construction, and in Matlab this is detected automatically, but the same was not happening in python.  We now explicitly call a real symmetric solver. 

Generally we probably need fewer than 10 values here, but when testing, we observed that asking for a different number of eigenvalues may return vectors which have different sign orientation, and that this would cause the unit tests to fail.  

It would be nice to understand this better.  Both under what circumstances the eigenvector results are different, and whether it is correct that the change in sign should cause different results (unit test to fail).

**Comment by junchaoxia** [comment]
From the recent updates on PR 163, we found the eigenvectors from `scipy.sparse.linalg.eigsh` is not stable. This is an ambiguous sign problem when repeating the calculation due to some internal randomness.   For example, the first rotation matrix in the saved npy file is listed as below:
> [ 9.45103184e-01 2.87087608e-01 -1.56079071e-01]
> [-5.63930012e-02 6.13766953e-01 7.87470607e-01]
> [ 3.21869229e-01 -7.35439211e-01 5.96262834e-01]

When the second run has the eigenvectors with different signs, it becomes as below:
> [ 9.45103184e-01 2.87087608e-01 -1.56079071e-01]
> [ 5.63930012e-02 -6.13766953e-01 -7.87470607e-01]
> [-3.21869229e-01 7.35439211e-01 -5.96262834e-01]

But the second one can be aligned to the first one by finding the global alignment matrix as below:

> [ 1.00000000e+00 9.54425519e-16 2.50147996e-15]
> [ 9.54425519e-16 -1.00000000e+00 4.67052110e-16]
> [ 2.50147996e-15 -3.21803771e-16 -1.00000000e+00]
 
So we are OK to the rotation estimation as long as we including the global alignment matrix for comparison.  To fix the ambiguous sign problem we have added the wrapper function `stable_eigsh` to make sure each repeated run will return the same eigenvectors. This is a similar sign problem as `scipy.linalg.eigh_tridiagonal` for PSWF2D basis class. Closing now.
