### ISSUE TITLE
Rotations-ish Class

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#213]
Upon review, code such as the following indicates it might be prudent to architect a class structure:

```
# Get register rotations after performing global alignment                                                                                                             
Q_mat, flag = register_rotations(rots_est, rots_true)
regrot = get_aligned_rotations(rots_est, Q_mat, flag)
mse_reg = get_rots_mse(regrot, rots_true) 
```

I haven't looked more deeply at what a design for this might look like.  It may have some relation to #208 .

**Comment by junchaoxia** [comment]
This should be related to how we should organize the util functions in a more generally way. Most of them are called by customized classes for different submodules of ASPIRE package but developed as individual functions in stead of class style. I will suggest to put these kinds of enhancements as lower priority since our most important goal now is a distributable minimum set of ASPIRE package.

**Comment by garrettwrong** [comment]
I sort of view this more as documenting incomplete work than an enhancement, but we already agreed to punt on this in order to let your code get through the PR, so I guess we agree for different reasons.

**Comment by janden** [comment]
> it might be prudent to architect a class structure

Agreed. It would essentially be a wrapper around `scipy.spatial.transform.Rotation`, which provides some of the basic functionality (to and from Euler angles, etc.). In line with the `Image` class, I think it would make sense for this class to represent a sequence of rotations (in analogy with a stack of images).

**Comment by junchaoxia** [comment]
This rotation class has been created on PR #195. Closing now.
