### ISSUE TITLE
Different normalization factors for FFB2D basis class and filter expanding 

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#250]
Current the normalization factors for the radial parts of FFB2D basis class and filter expanding are different but consistent with that of Matlab version. In the research paper on FFB basis, the normalization factor is `N_lk = 1/(c*sqrt(pi) *J_(l+1)(R_lk))`, with c=0.5 for radius cutoff, and J for the Bessel function. The normalization factor used for filter expanding, `N_lk = 1/(c *J_(l+1)(R_lk)*sqrt(1/2))`, does not include the `sqrt(pi)` but has an additional `sqrt(1/2)` as shown below:

https://github.com/PrincetonUniversity/aspire/blob/f152e8efd9856f75c294f453ef7846bd3a684410/projections/radial_filter_to_fb_mat.m#L43

In the implementation of FFB basis, `N_lk = 1/(c*sqrt(pi) *J_(l+1)(R_lk)*sqrt(1/2))` has an additional `sqrt(1/2)` to the paper as shown 

https://github.com/PrincetonUniversity/aspire/blob/master/basis/ffb_basis.m#L275
https://github.com/PrincetonUniversity/aspire/blob/master/basis/ffb_basis.m#L182

We should confirm that we need the different normalization factors.

**Comment by janden** [comment]
@junchaoxia Have you had a chance to look deeper into this?

**Comment by junchaoxia** [comment]
@janden Not yet. It is still on my list.

**Comment by janden** [comment]
Ok. Let's prioritize this. I'd like to find out what's happening exactly. It's perfectly possible that we need a different normalization factor, but we'd need to know why.

**Comment by junchaoxia** [comment]
@janden Not a problem. I will start to look it deeper after I fix the conflicts of the `rm_quaternions` branch.

**Comment by junchaoxia** [comment]
I have derived the normalization factors and gone through the code again. We do need different factors for FB basis classes and filter expanding.  For filter expansion we only need to do 1D expanding in radial direction and 1D integrating to get the normalization factor   `N_lk = 1/(c *J_(l+1)(R_lk)*sqrt(1/2))`, with c=0.5 for radius cutoff.  For the FB 2D basis we need to do expansion in both radial and theta parts and 2D integration to find the normalization factor,   `N_lk = 1/(c*sqrt(pi) *J_(l+1)(R_lk))`  as shown in the research paper.  In current implementation of Matlab and Python Code,  when `l` is not zero, `N_lk = 1/(c*sqrt(pi) *J_(l+1)(R_lk)*sqrt(1/2))` has an additional sqrt(1/2) to the paper. This is because we only use the positive frequencies for theta so the integration in theta only goes from `0` to `pi` instead of `0` to `2pi`.  In a summary, we are OK for the implementation.

**Comment by janden** [comment]
I don't understand. I see why we need a different normalization factor when integrating over radius compared to integrating over radius × angle. That makes sense. Since we only integrate over 0 to π, we only need to normalize by √π to make things work. So far so good. But then we divide by √2 for ℓ > 0. I don't think that has to do with only using positive frequencies since 1) dividing by √2 would yield a total normalization by √2π, implying integration over 0 to 2π and 2) that doesn't explain why we only perform that normalization for ℓ > 0.

My guess is that the different normalization for ℓ > 0 has something to do with the fact that there's only one angular basis function for ℓ = 0 (the constant one) while there are two for ℓ > 0 (one sine and one cosine).

**Comment by junchaoxia** [comment]
In FB 2D expansion, when I do integration over 0 to 2π for the theta part, the normalization for this part is sqrt(2π). It is sqrt(π) for integration over 0 to π. My understanding is based on the Matlab code (Line 287 to 289) as below, 
https://github.com/PrincetonUniversity/aspire/blob/master/basis/ffb_basis.m#L287

The number of theta is 2*n_theta, but only 0 to n_theta-1 points are generated. This might be corresponding to neglect all ℓ < 0. In the equation (15) of FFB paper, the ℓ  (denoted by k in paper) can go negative.

**Comment by janden** [comment]
Indeed, we integrate only over half of the frequency plane (corresponding to 0 to π). But my question is: why should this be different between ℓ = 0 and ℓ > 0? From your argument, for ℓ = 0 (when we have a normalization factor of √π), we would integrate from 0 to π, while for ℓ > 0, we would integrate from 0 to 2π. That doesn't make sense.

You also have to be careful in comparing the code to the paper. The angular part in the paper is a complex exponential, while in the code it's split into a sine and a cosine and it takes advantage of the Hermitian symmetry of the Fourier transform. That's why there is no ℓ < 0 in the code, because ℓ is not the same as k in the paper.

**Comment by junchaoxia** [comment]
For the current implementation, for ℓ = 0, it need to integrate from 0 to 2π (divided by sqrt(2π) for normalization same value in the paper). For  ℓ > 0, it need to integrate from 0 to π (divided by sqrt(π)). It makes sense if we think the missing sqrt(2) is due to the neglecting of ℓ < 0 since they are the same as as  ℓ > 0 and we only need to renormalize those ℓ > 0 by a factor of sqrt(2).

**Comment by janden** [comment]
> For the current implementation, for ℓ = 0, it need to integrate from 0 to 2π (divided by sqrt(2π) for normalization same value in the paper). For ℓ > 0, it need to integrate from 0 to π (divided by sqrt(π)).

No. The line from `ffb_basis.m` you reference above shows that *all* integrals go from 0 to π, regardless of ℓ = 0 or ℓ > 0.

> It makes sense if we think the missing sqrt(2) is due to the neglecting of ℓ < 0 since they are the same as as ℓ > 0 and we only need to renormalize those ℓ > 0 by a factor of sqrt(2).

As I said before, there is no ℓ < 0. In this code, ℓ < 0 has no meaning. It's not neglecting any coefficients ­– coefficients for ℓ < 0 are just not defined.

Please write down carefully what you are trying to say. The integration limits are the same for ℓ = 0 and ℓ > 0. Now why do we require a different normalization factor for ℓ > 0? Is it related to the fact that we have two basis vectors for the angular part?

**Comment by junchaoxia** [comment]
For  ℓ = 0 of FB 2D basis, there is an additional sqrt(2) as shown in the normalization function, 

https://github.com/PrincetonUniversity/aspire/blob/master/basis/ffb_basis.m#L182

So, the FB 2D normalization for ℓ = 0  is  `N_lk = 1/(c*sqrt(pi) *J_(l+1)(R_lk)*sqrt(1/2))`. In contrast, it is N_lk = 1/(c*sqrt(pi) *J_(l+1)(R_lk)) for  ℓ > 0.  My initial understanding is that this can be solved by integration over 0 to 2π for  ℓ=0, and 0 to π for  ℓ > 0.  Or we think it in the other way, for  ℓ  not zero, there are two set of basis functions for the same ℓ (ℓ < 0 and   ℓ > 0). But there is only one set of basis functions for  ℓ =0. I guess the later is more meaningful in mathematics as shown in the paper since all ℓs in the implementation have the same number of thetas.

**Comment by janden** [comment]
> So, the FB 2D normalization for ℓ = 0 is `N_lk = 1/(c*sqrt(pi) *J_(l+1)(R_lk)*sqrt(1/2))`. In contrast, it is `N_lk = 1/(c*sqrt(pi) *J_(l+1)(R_lk))` for ℓ > 0.

Yes. We've established this several times now.

> My initial understanding is that this can be solved by integration over 0 to 2π for ℓ=0, and 0 to π for ℓ > 0.

Right, but as we see, the integration limits are the same for both cases, so that cannot be what's happening.

> Or we think it in the other way, for ℓ not zero, there are two set of basis functions for the same ℓ (ℓ < 0 and ℓ > 0). But there is only one set of basis functions for ℓ =0.

How is that equivalent to having different integration limits? What do you mean by ℓ < 0? As we've established above, there is no ℓ < 0 in the code. Are you referring to the `sgn` variable, which takes values –1 and +1 for ℓ > 0?

> I guess the later is more meaningful in mathematics as shown in the paper since all ℓs in the implementation have the same number of thetas.

I don't understand. There are no ℓs in the paper.

**Comment by junchaoxia** [comment]
If we check the paper, the ℓ in the implementation should be the `k` in equation (15), which can go from `-k_max` to `+k_max`. Do  the `k` from `- k_max` to `-1` correspond to the cases of ℓ < 0? In the implementation I can not find which part is related to those. That's the reason I initial think ℓ < 0 is neglected. But it looks that this can be simplified as somewhere such as from line 585 to 607
https://github.com/PrincetonUniversity/aspire/blob/master/basis/ffb_basis.m#L585
in the form of `ind_neg`. I believe this is what your meanings of  `sgn` variable which takes values –1 and +1 for ℓ > 0. If this have been taken care of I am not sure the reason for the difference of sqrt(2).

**Comment by janden** [comment]
> If we check the paper, the ℓ in the implementation should be the `k` in equation (15), which can go from `-k_max` to `+k_max`. 

I've said this several times now: The implementation does not correspond exactly to the formulas in the paper. The indices k and ℓ are *not* the same. The paper uses k to signify the angular frequency in the complex exponential. The code has no complex exponentials (as you can see), but sines and cosines whose angular frequency is ℓ. That changes things. They are related, but they're not the same.

> Do the `k` from `- k_max` to `-1` correspond to the cases of ℓ < 0? In the implementation I can not find which part is related to those. That's the reason I initial think ℓ < 0 is neglected.

Again, there is no ℓ < 0 because ℓ < 0 does not make sense. It's not neglected, it's just not defined.

> But it looks that this can be simplified as somewhere such as from line 585 to 607
> https://github.com/PrincetonUniversity/aspire/blob/master/basis/ffb_basis.m#L585
> in the form of `ind_neg`.

It looks like what can be simplified? I don't understand.

> I believe this is what your meanings of `sgn` variable which takes values –1 and +1 for ℓ > 0. If this have been taken care of I am not sure the reason for the difference of sqrt(2).

If what has been taken care of?

Please take the time to sit down and try to work out what the code is doing. What is it calculating, exactly? At the end of the day, you'll have a sum of some sort. As I said, it's not the same as the paper, but it's equivalent (for real images). In other words, the coefficients in the code can be converted to the coefficients in the paper, and vice versa. Once you have these things written out and you know what they are, it should be easier to figure out what the proper normalization should be and why.

**Comment by junchaoxia** [comment]
Read the paper and code again. From the equation (2) of FFB paper I understand the basis functions are represented by
<img src="https://render.githubusercontent.com/render/math?math=N_{k,q}J_k(R_{k,q} r/c)e^{i k \theta}">
where k can be negative, zero and positive. In the code implementation, the k is changed to  ℓ and only take non negative values. My recently understanding is that `ind_pos`  and `ind_nag` variables are used to control this negative and positive of  ℓ to reproduce k in the paper. But actually from your comments, it is not in this way. They are used to represent the sin ans cosine parts. So the basis functions are different in the implementation and they are represented by sine and  cosine parts such as, <img src="https://render.githubusercontent.com/render/math?math=M_{k,q}J_k(R_{k,q} r/c)cos(k \theta)"> and <img src="https://render.githubusercontent.com/render/math?math=M_{k,q}J_k(R_{k,q} r/c)sin(k \theta)">.
The normalization integration in the angular part for the paper is 
<img src="https://render.githubusercontent.com/render/math?math=\int e^{ik \theta}e^{-ik \theta}d\theta = 2\pi"> which can be separated as <img src="https://render.githubusercontent.com/render/math?math=\int cos(k\theta)^2\d\theta"> + <img src="https://render.githubusercontent.com/render/math?math=\int sin(k\theta)^2\d\theta">. 
So the integration in angular parts of sine and cosine parts are <img src="https://render.githubusercontent.com/render/math?math=\int cos(k\theta)^2\d\theta = \int sin(k\theta)^2\d\theta =\pi ">. 
Based on this analysis, for   ℓ = 0, there are no sine and cosine parts, the integration is still 2π. But for  ℓ > 0, there are both sine and cosine parts,  and the integration only gets π. That is the reason we have to adjust the normalization factors of basis function differently.

**Comment by janden** [comment]
Yes this makes a lot of sense. So the angular component of the basis has a different normalization constant for ℓ = 0 and ℓ > 0 since the former only has one basis vector, while the latter all have two each.

So a way to do this elegantly would be to make sure the `radial` attribute is properly normalized for the radial part, then store another vector that contains the normalization factors for the different angular components. This way, when the radial part is accessed from `fb_mat`, it doesn't need any extra normalization. Only in `FFBBasis2D.evaluate` and `evaluate_t` do we add the extra normalization factor since we do a 2D integration there.

**Comment by junchaoxia** [comment]
This issue was solved in PR #284. Closing now.
