### ISSUE TITLE
CTF information from metadata of ImageSource class

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#301]
From updates of PR #295, we removed the `filters` attribute of ImageSource class and the `_filters` column in metadata for storing CTF filter objects for all images, and changed to use filter types and indices. Although there might be beneficial to keep metadata as the pandas table in the similar length of Relion star file for input and output, it might be better to remove the redundant CTF information in the metadata and only use the information from the unique filter types.  In this case we need to rebuild the complete metadata table when coming to save the star file with CTF information.

**Comment by garrettwrong** [comment]
@chris-langfield , can you check if this is issue is still relevant?

**Comment by chris-langfield** [comment]
The question being asked here is: 


> Rather than storing CTF parameters in the metadata table for each particle (redundantly, as many particles share the same parameters as indexed by `ImageSource.filter_indices`), shouldn't we just create the `CTFFilter` objects (stored in list `ImageSource.unique_filters`), and read the information from these objects when it's needed? In particular, when saving an `ImageSource`, the CTF metadata could be read from the `unique_filters` and written into metadata only at the point where it is being saved into a STAR file.

#### `RelionSource` and `CoordinateSource`

For `RelionSource` and `CoordinateSource` objects, all CTF information is coming from STAR files which already store this data "redundantly" in a big table. This is read in as a `pandas` table, and we use the `_rlnVoltage`, `_rlnDefocusU`, etc. columns to *create* the `CTFFilters`. We also need to create these columns when saving the sources. So implementing the above change would amount to deleting all of those columns after reading them, but then recreating them again.

The CTF parameters are stored as `float64`, and there are 6 of them. Meaning that for a 100k image source, we're using up about `100k * 6 * 8 bytes = 4.8 MB` of memory by keeping them in the `pandas` table. Not sure if this is bad enough to justify making the change.

See:

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/ee21ca750a3e93d22a14f57285b105746b4fdf4d/src/aspire/source/relion.py#L145-L166

and

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/ee21ca750a3e93d22a14f57285b105746b4fdf4d/src/aspire/source/coordinates.py#L253-L286

#### `Simulation`

For `Simulation`, it works the other way around. `CTFFilters` are either passed in as `unique_filters` in construction, or generated randomly. The metadata is then constructed based on those:

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/ee21ca750a3e93d22a14f57285b105746b4fdf4d/src/aspire/source/simulation.py#L120-L153

------

All the sources have the same `ImageSource.save` mechanic, which converts the metadata into a STAR file as-is.

Currently, this CTF metadata is **not** mutable under any situation. For every Source, it is created at the time of construction, and changing the `CTFFilter`s themselves never updates the metadata. So even if the source is downsampled or anything else, changing the filters, saving the image will preserve the original metadata.

The answer to the question at the top depends on what the doctrine should be going forward for `ImageSource` metadata. If we do want it to be mutable, then we would need to implement something like this in any case, because we'd be depending on the state of the filters to update the metadata as new transformations are applied.

**Comment by garrettwrong** [comment]
I'll need to think about this:

>and changing the CTFFilters themselves never updates the metadata. So even if the source is downsampled or anything else, changing the filters, saving the image will preserve the original metadata.

 My initial impression is that might not be the behavior we want.

**Comment by garrettwrong** [comment]
Even for a million images, this would be sub 100MB, I'm really not sure it is worth the complexity to pack and unpack the CTFs.  This is especially true if we are moving towards per-image-ctf being commonplace.

Thanks for the helpful discussion.  I agree that anything further on this issue is actually more a question of mutable/immutable sources. 

Closing.
