### ISSUE TITLE
Docstring Cleanup and Automatic checking

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#330]
There are tools to automatically check/lint our doc strings and which can be integrated into tox with the other code qa tools.

I have run the style checker to see our conformance and I think it would be a fair amount of work to get the code over the initial hurdle, so I've broken this off of #220 into it's own issue.

**Comment by garrettwrong** [comment]
Josh, I think you were already looking into this with me the other day.

Lets look at i) what doc style options ii) linters/automated tools iii) interaction of i/ii and what that implies for our code.

If there is a way we can standardize and automate things without spending a lot of developer time, that would be great.

**Comment by garrettwrong** [comment]
Let's try to address this systematically starting with the application of`pydocstyle` to actual errors.  Adding to current project.

**Comment by j-c-c** [comment]
Here is a summary of errors from `pydocstyle` (actually `flake8`s extension for `pydocstyle`):

Total Errors: 3069

Itemized Errors:
Missing docstring ...: 1101
One-line docstring should fit on one line: 406
First line end with period: 518
Blank line required between summary and description: 348
No blank lines allowed after docstring: 433
Use imperative mood: 236
First word needs to be capitalized: 15

I will take a look at options for auto-formatters and determine if we can go that route or if we need to cleanup with `RegEx`.

**Comment by j-c-c** [comment]
I've found two docstring auto-formatters which appear to be regularly maintained, [`docformatter`](https://docformatter.readthedocs.io/en/latest/index.html) and [`pydocstringformatter`](https://pypi.org/project/pydocstringformatter/).

`pydocstringformatter` is based off of `docformatter` but addresses some issues of the latter. After testing out both it seems like `pydocstringformatter` would work better for us since it resolves one of the main issues causing our docs to improperly render. Namely, a missing blank line between the docstring summary and description. `docformatter` actually creates more of these blank lines! 

After cleaning up with `pydocstringformatter` the majority of the remaining errors are for "missing docstrings" and "blank lines after a docstring". We could ignore the first error (since it would involve manually adding a few hundred unique docstrings) and I could clean up the second error manually with sed.

There does appear to be a few instances of unwanted (or improper) reformatting, but I could probably address those individually if I carefully auto-format one module at a time.

`pydocstringformatter` has minimal dependecies (requires `tomli`) and supports python 3.8 - 3.12.

**Comment by garrettwrong** [comment]
That sounds great, thanks Josh!

**Comment by janden** [comment]
Great initiative. Thanks!

**Comment by j-c-c** [comment]
A little follow up after a deeper look at both `docformatter` and `pydocstringformatter`:

1) **Doc Breaking Error:** 

- It turns out that neither of these options fixes the thing that breaks our docs, ie. a missing blank line between a docstring description and the parameters section. It should be mentioned that `pydocstyle` does not throw an error when this occurs. It turns out that the "missing blank line" errors mentioned above were indicating that we do not have a single-line "summary", followed by a blank line, then followed by a "description" section. So we will probably have to find and fix instances of the "missing line above param section" manually.

2) **Missing Blank Line Error:** 

- `pydocstringformatter` cleans up most of the "missing blank line" errors thrown by `pydocstyle`, but it expects there to be a single line summary in every docstring. If there is not one, (ie. if there is just a long description of a method), it will cut off the first ~79 characters of the description, add a period and a new line, and use the remainder of the text as the "description" section. This makes quite a bit of mess to clean up since it mostly just cuts sentences in half. 

- `docformatter` does not fix this error. It actually causes more instances of this error since it line wraps summary sections at 79 characters causing a single line docstring to become two lines (ie. `pydocstyle` reads this second line as a "description" section with no blank line above).

3) **First line end with period Error:**
- `pydocstringformatter` fixes this error.
- 'docformatter` does not.

4) **One-line docstring should fit on one lineError:**

- Both formatters fix this.

5) **No blank lines allowed after docstring Error:**

- Neither formatter fixes this.

6) **Line Wrapping:**
- Another downside to `pydocstringformatter` is that it's functionality for wrapping a section by character count doesn't work. 
- `docformatter` line wrapping works.

Ultimately, if we want to integrate some docstring qa into tox we'll have to do some serious cleanup first. I might be able to do some manual cleanup and then follow with one of the formatters to get us where we need to be.

**Comment by garrettwrong** [comment]
> Here is a summary of errors from `pydocstyle` (actually `flake8`s extension for `pydocstyle`):
> 
> Total Errors: 3069
> 

Are these specifically on `src/aspire` or on the entire repo (including `tests/`)?

**Comment by j-c-c** [comment]
> > Here is a summary of errors from `pydocstyle` (actually `flake8`s extension for `pydocstyle`):
> > Total Errors: 3069
> 
> Are these specifically on `src/aspire` or on the entire repo (including `tests/`)?

These were on the entire repo. I am actually getting a different number now when I run flake8, which is a little confusing. At any rate, when I rerun this in a clean environment i get the same value. So 1045 out of the 3069 are from tests.

**Comment by garrettwrong** [comment]
Let's not consider `tests` directory in this discussion.

**Comment by j-c-c** [comment]
> I am actually getting a different number now when I run flake8, which is a little confusing. 

Mystery solved: I installed `darglint` to test it out and `flake8` is picking it up and running it.

**Comment by garrettwrong** [comment]
Still catching up with all the reporting here.  This issue isn't going as effectively as I hoped. Looks like we should have had the intern that typed 148wpm work on our documentation. 😆 

Noting if it is decided to do any sweeping docstring cleanup it would be best to do it at the very beginning or end of a release cycle, or at some point when minimal other PRs are in flight.  (min merge conflicts).  By sweeping I mean something like wrapping that would potentially alter every file.

----------

If these tools are not doing what we need, or exploring them is becoming  inefficient, I'm still sure we can conquer (1) with a script.  We've discussed writing a script that resolves the line breaks programmatically then reusing that logic/regexp as a check script to be added into the repo for CI.  Minimally this should be done to close the issue if no tool presents itself as a good solution.

There are roughly 60-70 occurrences across 30 of 100+ src python files.  Sounds small but doing manually would be searching/reading through 30k+ loc. Which is gross and doesn't actually add anything to CI.  

After that it would be possible to add minimal other checks that focus on doc issues we are concerned with over time, ad hoc.

Let's continue to see if some of the alternative tools help the codebase in a meaningful way, and decide which if any of these formatters are worth applying.  If none of them solve (1) we'll need to write that script to close the issue.

**Comment by j-c-c** [comment]
Sounds good. I explore some other formatters to see if any solve (1). If not, then a script it is!

**Comment by garrettwrong** [comment]
Updating with this mornings catch up.  Seemed like none of the tools solved the most pressing problem, but you were able to make a patching script to apply updates (changes to be pushed as a PR), and will convert to a script that will be added to the CI checks (as another PR).  

That should be enough to close this issue, but after trying the formatters more, was there anything of value that we would want to apply/enforce to the codebase in the near term (this release cycle)? Thanks

**Comment by j-c-c** [comment]
It seems like most of the formatters expect the docstrings to have a particular layout, ie. having a one-line summary followed by a description body. If there isn't this general layout they exhibit some funny behavior. For example, only line-wrapping the first paragraph of a docstring. So I'm not sure the formatters offer us much that we can't fix on our own.

**Comment by j-c-c** [comment]
Covered in #1022. Closing.
