### ISSUE TITLE
dtype in Relion ImagSource class 

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#338]
It looks the images are created as float64 even the dtype of Relion object is set to float32.

**Comment by garrettwrong** [comment]
Hrrm, sorry about that. I guess after doing so many one or two might have slipped by in less used code. Since that was relating to my recent work I went ahead and put a patch up.

RelionSource doesn't have a dtype to set, it should pick it up from the file. The empty array initialization in `_image` method (for copying data or something) was missing a dtype=self.dtype. 

Maybe adding this kind of check to the unit tests would be good ( I would have liked to check things across the board but time didn't allow), probably in `tests/test_starfile_stack.py`.

**Comment by garrettwrong** [comment]
Minor patch has been merged in, closing.
