### ISSUE TITLE
Add save function in Volume class

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#367]
The volume class needs a save function to output density maps to a mrc file.

**Comment by janden** [comment]
I think it's better if all IO stuff live in `aspire.storage`. The `Volume` and `Image` classes should be independent of application.

**Comment by garrettwrong** [comment]
@j-c-c , since you are working in `Volume` already, we can make a small PR to cover this.  I don't think it will be too much work.

Documentation regarding how to use mrcfile is here: https://mrcfile.readthedocs.io/en/latest/usage_guide.html

I think for an initial pass we should simply support writing to MRC only (not .map), and an associated unit test.

For completeness, some Map file details can be found here:
https://www.emdataresource.org/mapformat.html
https://www.ccp4.ac.uk/html/maplib.html
https://www2.mrc-lmb.cam.ac.uk/research/locally-developed-software/image-processing-software/

**Comment by garrettwrong** [comment]
Closed by 514
