### ISSUE TITLE
Unncessary method in ImageSource

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/ASPIRE-Python#43]
Regarding `ImageSource.eval_filters()`..

I'm also not clear on what this function does. It takes a NumPy array, converts it to a set of `Image` objects, filters them, and converts back to NumPy. Why do we want to do this? It also doesn't fit with the name `eval_filters`, which suggests that we're calculating the filter values for some set of frequencies. As discussed below, it's also not clear that this should be a function of the `ImageSource` object itself, since it principally relates to the filters.

_Originally posted by @janden in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3Mjg0NjA5ODgz/pull_request_reviews/more_threads_

**Comment by garrettwrong** [comment]
@chris-langfield , does this issue relate to your recent work with `eval_filter_grid`?  Thoughts?

**Comment by chris-langfield** [comment]
From what I can tell, the methods have very different functions despite the names:

`eval_filter_grid` returns the grid of values that will be multiplied by the FT of the image. The filter's kernel in frequency space is a function only of the frequency gridpoints, not the Image itself. It only uses the *shape* of the source and then the source's filters to create this kernel. This is moved to `filters` in #517 

`eval_filters` applies the actual filter to the image via the `Image.filter()` method. So the FT of the actual image is computed, and multiplied by the filter kernel. It's used by `ImageSource.im_backward` and `ImageSource.vol_forward`, which themselves take Volumes or Images as arguments. 

It seems like these were put in `ImageSource` because they use a source's filters, shifts, etc, and apply them to a given volume.

**Comment by janden** [comment]
> `eval_filters` applies the actual filter to the image via the `Image.filter()` method. So the FT of the actual image is computed, and multiplied by the filter kernel. It's used by `ImageSource.im_backward` and `ImageSource.vol_forward`, which themselves take Volumes or Images as arguments.

Yeah that sounds like a misnamed method, what about `apply_filters`? If it's only used internally, it should also be private, so `_apply_filters`?

**Comment by chris-langfield** [comment]
#526 was merged, I believe the issue was addressed.
