### ISSUE TITLE
Existence of `BFSRAlign2D` and possible enhancement

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#570]
First question is whether `BFSRAlign2D` is still needed in view of #538 being merged. If we do want to keep it, it would make sense to bring the shift calculations in line with those used in `BFSReddyChatterjiAlign2D`.

**Comment by garrettwrong** [comment]
It would not be too hard to make the search be a disk like the other methods and then use the parallelization technique.  Because this is a stupid simple algo that can be used for d3eveloper reference, I think it might be worth leaving as long as it is under sufficient unit testing.  I'm thinking to take this after #660 .

**Comment by garrettwrong** [comment]
Disk search and batching implemented in #755. Closing
