### ISSUE TITLE
Allow `Basis` objects to take a scalar input instead of tuple for size

### ISSUE THREAD

**Issue by janden** [ComputationalCryoEM/ASPIRE-Python#592]
Since these are all required to be square anyhow, it would be useful to have a shorthand of a scalar size that corresponds to that square.

**Comment by chris-langfield** [comment]
Since `size` is currently the required argument for creating a `Basis`, it would still have to be supplied even if we added a shortcut (let's say we called it `L`). 

There isn't a plan to support expanding rectangular images in one of these bases, right? I would propose to just ditch the tuple and always supply an integer
