### ISSUE TITLE
problem of reading star file 

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#64]
The IO codes for reading star file need more extensive tests. The current version has problem to deal with star files without originX and originY columns and additional None type data appeared at the first row probably due to parsing the blank lines.

**Comment by vineetbansal** [comment]
The particular error we're seeing is because the StarFile class was not equipped to handle commented lines. This is fixed in 068f23bf3f47259580dba1d95840f5337e87ac7e. Let's keep this open till the general problem of missing columns (which should take on a default value) is handled.

**Comment by garrettwrong** [comment]
@chris-langfield I think this relates to #519

**Comment by chris-langfield** [comment]
Loading a `RelionSource` (which uses the new `StarFile` implementation) can handle any number of metadata columns missing. This is the code that loads in the columns:

```python
column_types = {name: cls.metadata_fields.get(name, str) for name in df.columns}                                                       
df = df.astype(column_types) 
```
The only explicit column that is required is `_rlnImageName` because this contains the index and stack of each particle. 

I was able to load a `RelionSource` from a star file with `_rlnOriginX` and `_rlnOriginY` columns removed.

The testing for STAR file IO, including Read, Write, Read back, and Write, Read, Write back and compare, was expanded by #486 

Handling of comments, blank entries, etc. has been offloaded to the `gemmi` library.

I believe this issue is largely separate from #519, as it isn't affected by *where* the STAR IO is happening. 

We decided that Relion columns should *not* be created with default values in the event that they aren't in the STAR file. So the current behavior I think makes sense.
