### ISSUE TITLE
`Volume.T` does not match `numpy` Transpose

### ISSUE THREAD

**Issue by chris-langfield** [ComputationalCryoEM/ASPIRE-Python#644]
The `Volume` class has a `.T` property which returns the transpose of the data. However, this does not match the `numpy` transpose operation on the volume's data

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/1bff8d3884183203bd77695a76bccb1efc909fd3/src/aspire/volume/__init__.py#L202-L223

Reproduce:

```python
from aspire.volume import Volume
import numpy as np
data = np.random.rand(8,8,8)
v = Volume(data)
v.shape # (1, 8, 8, 8)
v.T.shape # (1, 8, 8, 8)
v.asnumpy().T.shape # (8, 8, 8, 1)
```

This specifically comes up in `FBBasis3D.evaluate_t` as the method calls for `v.T`, which means different things depending on whether it is a Volume or an array.

We should clarify the intent of the `.T` operation of the Volume class.

**Comment by garrettwrong** [comment]
Hi Chris, I don't feel this `transpose` is meant to duplicate numpy exactly. This is why the docstring states it will flip the data axes and also why the code is written out so explicitly for that method... (where a one liner could do). Trying to make it pretty clear we are only operating on the data axes (not the stack axis).

In `image` we use the method name `flip_axes`, but in 3d this sort of collides with the existing `flip` method, which is a different hack (that one reverses an axes, joy) :).

ASPIRE is going to need a way to transpose the Volume instances' data, and it will almost never mean the stack axis... For that you are right, we should just use .asnumpy().T.  If there are places that transpose the stack axis, they just need to get resolved (this is probable in the 3d code).

If you found this causing a bug, that is probably my mistake and a good catch, thank you.

**Comment by garrettwrong** [comment]
If you want to propose a solution that reconciles the names for all the cases and are willing to implement it as a standalone patch it would probably be well received :).

**Comment by chris-langfield** [comment]
Thanks for explaining, yes I see now why this came up. It definitely wasn't a bug, just something that came up while switching around functions taking/returning `Volume`s vs NumPy arrays. 

I actually think that the `asnumpy().T` probably (hopefully) only comes up internally and the more natural thing a user would want to do is flip just the data axes. Maybe we can leave it, or maybe something like `transpose_data()` for both `Image` and `Volume`?

**Comment by garrettwrong** [comment]
I agree that there is a bit too much discrepancy between Image and Volume.

Image provides `flip_axes` for transposing the data `transpose(self.data(0,2,1))`

Volume provides `flip` for reversing an axis `np.flip(self.data, axis)` 
and provides `transpose` `T` for transposing the data ``transpose(self.data(0,3,2,1))` (although it coded as a loop, which we should change).

######

`Image.flip_axes` appears to only be used in tests.
`Volume.flip` is only used in Volume, tests, and `commonline_base.py`
Volume transpose would require me to write a script to find occurances.

######

I do like the `.T` short hand and feel it is okay to have `transpose` do the right thing for our class instead of exactly what numpy would do to the underlying array.  Although I'm okay with taking a vote during a team meeting.

My inclination is to use `flip` for reversing an axis, `transpose` and `T` for transposing data... for both `Image` and `Volume`.

That would also be lower risk since the main thing to change would be least used... `Image.flip_axes`.
