### ISSUE TITLE
Phase Flipping (for CTF Correction)

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#650]
Yoel reported (by email) that ASPIRE CTF `phase_flip` was not working.

This isn't part of the code I implemented, so I need to get farther into details, but shown below is code in question.  If I am reading the code for `LambdaFilter` correctly, it will first evaluate the `self.unique_filters` on a frequency grid `omega`, and then the result of will be passed into `np.sign`.  Crudely, `np.sign(f(*omega))`.

```
         logger.info("Perform phase flip on source object")
         logger.info("Adding Phase Flip Xform to end of generation pipeline")
         unique_xforms = [
            FilterXform(LambdaFilter(f, np.sign)) for f in self.unique_filters
         ]
         self.generation_pipeline.add_xform(
             IndexedXform(unique_xforms, self.filter_indices)
```

To be continued...

**Comment by garrettwrong** [comment]
Been going back and forth with Yoel, couple red herrings, but I think I figured the problem out.

Their example starfile (attached) was missing `_rlnVoltage` `_rlnSphericalAberration` and `_rlnAmplitudeContrast`.

In current ASPIRE code, if a complete set of CTF params is not provided, the branch to create CTFFilter objects is not run and no filters are added to `self.unique_filters`.  This results in `phase_flip` being a no op. ( Technically it operates, but over a single IdentityFilter).

When I added the missing fields with some guessed values the CTFFilters were created into `self.unique_filters` and `phase_flip` code was exercised.

I think we might want to guard against this by:
i) add some logging to indicate the number of CTF filters found
ii) raise error if user calls `phase_flip` with no CTF filters


[phase_flip_test.tgz](https://github.com/ComputationalCryoEM/ASPIRE-Python/files/9059123/phase_flip_test.tgz)

I'll follow up again after confirmed with Yoel.

**Comment by janden** [comment]
Yeah I'd say that this should be expected behavior. If a user supplies a STAR file with incomplete CTF information, it's expected that we don't create the CTF filters. The question is whether we should error (indicating that the STAR file is misformatted) or log/emit a warning. Normally, we're quite permissive, so I guess we should consider the latter.

Calling `phase_flip` *should* be a no-op if we don't have filters. I don't think a user should be punished if they include it even if it's not necessary. Consider `invert_contrast`. If the images are already positive, this is also a no-op.

**Comment by garrettwrong** [comment]
Okay, re punishment, my draft #654 currently raises an error if `phase_flip` is called without any filters.  This was following the suggestion of Yoel.  It's easy enough (two or three lines) to change to a warning and continue.  I'll do that and undraft it. Thanks.

**Comment by garrettwrong** [comment]
Closed by 654.
