### ISSUE TITLE
Rectangle MRC input to ctf_estimator

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#651]
User reported an issue using rectangular MRC files with ctf_estimator as #558 .

- [x] Create a unit test for this if it does not already exist.
- [x] Confirm the behavior/bug.
- [x] If the suggested patch is correct, rebase the original contributor's patch.  Otherwise we should improve example/doc here for future users.

**Comment by chris-langfield** [comment]
So `mrcfile` does in fact save the Y axis as 0 and the X axis as 1:

> mrcfile follows the Python / C-style convention for axis ordering. This means that the first index is the slowest axis (typically Z for volume data or Y for images) and the last index is the fastest axis (typically X), and the numpy arrays are C-contiguous

see https://mrcfile.readthedocs.io/en/latest/usage_guide.html

The reason for the error when loading rectangular micrographs is the following line:

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/1bff8d3884183203bd77695a76bccb1efc909fd3/src/aspire/ctf/ctf_estimator.py#L154-L160

The `i`s and `j`s need to be switched because of the axes convention noted above.

I think the fix and adding a unit test for this should wait until after #623 is merged as this modifies `ctf_estimator` significantly

**Comment by chris-langfield** [comment]
Draft test sitting in branch `rect_ctf_651`

**Comment by chris-langfield** [comment]
Closed by #688
